### ISSUE TITLE
Create Folders specific to language ex. python, C, ruby etc.

### ISSUE THREAD

**Issue by achoudh5** [achoudh5/Interview_Questions#2]

**Comment by Nevin243** [comment]
Hey @achoudh5 I can pick this up!

top 15 languages or so do?

**Comment by achoudh5** [comment]
Sounds good @Nevin243 . I have kept it open, contribute as much.
Thanks :)

**Comment by phillipknight** [comment]
How were you envisioning submissions working/in what format for the interview questions?
